# Generated by Django 4.1.1 on 2022-09-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagementtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
