# Generated by Django 4.1.1 on 2022-09-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagementtest', '0002_alter_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='stripe_payment_intent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
