# Generated by Django 4.1.1 on 2022-09-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagementtest', '0003_alter_orderdetail_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_details',
            name='event_image',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
