# Generated by Django 4.1.1 on 2022-09-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagementtest', '0004_event_details_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
