# Generated by Django 4.1.1 on 2022-09-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagementtest', '0005_register_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanagementtest.event_details', verbose_name='Product'),
        ),
    ]
